// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// The Prisma CLI (migrate/studio) only accepts a single connection string, so
// for remote libsql/Turso URLs we append the auth token as a query param.
// The app runtime (src/lib/db.ts) uses the PrismaLibSql adapter's separate
// `url` + `authToken` fields instead — this composed URL is CLI-only.
const rawUrl = process.env["DATABASE_URL"];
const authToken = process.env["DATABASE_AUTH_TOKEN"];
const cliUrl =
  rawUrl && authToken && rawUrl.startsWith("libsql:")
    ? `${rawUrl}${rawUrl.includes("?") ? "&" : "?"}authToken=${authToken}`
    : rawUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: cliUrl,
  },
});
